Traceback (most recent call last):
  File "/usr/share/miniconda/envs/buildjupyterbook/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/miniconda/envs/buildjupyterbook/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda/envs/buildjupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/buildjupyterbook/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/buildjupyterbook/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/share/miniconda/envs/buildjupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda/envs/buildjupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda/envs/buildjupyterbook/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import madrigalWeb.madrigalWeb

#constants
madrigalUrl = 'http://cedar.openmadrigal.org'

user_fullname = 'Jonathan Makela'
user_email = 'jmakela@illinois.edu'
user_affiliation = 'University of Illinois'

# create the main object to get all needed info from Madrigal
madrigalObj = madrigalWeb.madrigalWeb.MadrigalData(madrigalUrl)

# Lowel FPI
code = 5555

expList = madrigalObj.getExperiments(code, 2023, 5, 10, 0, 0, 0, 2023, 5, 12, 0, 0, 0)

for exp in expList:

    fileList = madrigalObj.getExperimentFiles(exp.id)
    
    for file in fileList:

        outFile = os.path.join(asi_directory, os.path.basename(file.name))
        print(outFile)
        madrigalObj.downloadFile(file.name, outFile, user_fullname, user_email, user_affiliation, format='hdf5')

------------------


[31m---------------------------------------------------------------------------[39m
[31mNameError[39m                                 Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[2][39m[32m, line 24[39m
[32m     20[39m fileList = madrigalObj.getExperimentFiles(exp.id)
[32m     22[39m [38;5;28;01mfor[39;00m file [38;5;129;01min[39;00m fileList:
[32m---> [39m[32m24[39m     outFile = [43mos[49m.path.join(asi_directory, os.path.basename(file.name))
[32m     25[39m     [38;5;28mprint[39m(outFile)
[32m     26[39m     madrigalObj.downloadFile(file.name, outFile, user_fullname, user_email, user_affiliation, [38;5;28mformat[39m=[33m'[39m[33mhdf5[39m[33m'[39m)

[31mNameError[39m: name 'os' is not defined

